### ISSUE TITLE
[SUGGESTION] - PD Impound Details / History Added 

### ISSUE THREAD

**Issue by CloudTheWolf** [teddythedev/legacy-mdt-issue-tracker#12]
**Summary:**
_NOTE: This would require an OPFW Change as well_

On the dashboard, add a live "Held Vehicles" panel so officers can see what vehicles are being held, and how long is left until release. 

Additionally, sync PD Impounds, Duration and impounding /releasing officer so that this could be used to dynamically link impounds to reports / incidents 

Eg.

| id | Vehicle | Registration | Officer | Duration | State | Released By |Impound Time (UTC)|
| -- |----------------|------------|------------------|--|-----------|---------------|-----------------|
|1|Declasse Asea |12ABC345|Chase Sandwich|90|Released|Chase Sandwich|2022-01-01 12:00|
|2|Declasse Asea |12ABC345|Chase Sandwich|90|Released|Automatically Released|2022-01-01 14:00|

When a vehicle is sent from PD Impound to State Impound Automatically the "Released By" could be "Automatically Released"

**Reason:**
Why would your suggestion be a good change for the MDT?
This would allow officers to more efficiently review held vehicles and allow a history of when a vehicle was impounded / released.

**Comment by teddythedev** [comment]
Twootie is making the API to get active holds. Not sure if they contain a history or not. Once that’s there I’ll implement it

**Comment by teddythedev** [comment]
Very basic version of this is out right now, going to implement it further here soon with better model name among other things, just wanted to get something out there for now.

**Comment by CloudTheWolf** [comment]
> Twootie is making the API to get active holds. Not sure if they contain a history or not. Once that’s there I’ll implement it

For the mechanic sites, the Tow Impound Endpoint Only showed Impounds a player did if they are still in city, ~15 after the flew out this was no longer available. To get around this I Polled the API every 5 mins and wrote all impounds the my local DB, so you may have to do a similar thing potentially. (Basically what you currently do with the Characters endpoint)

**Comment by teddythedev** [comment]
So the impounded vehicle stuff is just attached to the players vehicle so it doesn't matter if the person is in or out of the city so it makes it easier. She got the endpoint done and its out there right now, doesn't need to poll like the characters endpoint.
