### ISSUE TITLE
[SUGGESTION] - Clickable link on arrests records to go to suspects profile page

### ISSUE THREAD

**Issue by Masik52** [teddythedev/legacy-mdt-issue-tracker#14]
**Summary:**
When looking at the arrest records on incidents it would be nice if we had the ability to click the suspects name and have it open their personal MDT profile.

**Reason:**
You would be able to easily add something to their profile if needed rather than having to leave the incident and go to the profile tab to search for their profile.

**Comment by teddythedev** [comment]
![image](https://user-images.githubusercontent.com/47933692/192111480-c3d07042-9710-4b76-aed9-12112d1dd5fb.png)

Clicking the name on the arrest will now lead you to their profile in a new tab. I am pretty sure that is what you meant so just let me know if I was way wrong lol

**Comment by Masik52** [comment]
Yes that is
