### ISSUE TITLE
[SUGGESTION] - Add Date of birth to MDT profiles 

### ISSUE THREAD

**Issue by northbayjoe** [teddythedev/legacy-mdt-issue-tracker#17]
**Summary:**
Pull the suspects date of birth from their server info to the MDT profiles

**Reason:**
This would help us use this info to determine if a person is giving us a false name if they didn't know what day they were born, cause let's be real, who doesn't know their birthdays... Liars don't that's who lol..

**Comment by teddythedev** [comment]
Already pulling that info back, so I will get that added to the UI here.

**Comment by teddythedev** [comment]
Pushed on last update. Moved the CID to after the name and added DOB!

**Comment by teddythedev** [comment]
![image](https://user-images.githubusercontent.com/47933692/207518556-2cb2c9ce-9e52-4de7-bf86-fde0a30d7ffd.png)
