### ISSUE TITLE
Marking Officers 10-7 10-8 Etc

### ISSUE THREAD

**Issue by rustyjohn1** [teddythedev/legacy-mdt-issue-tracker#20]
Hi bud, got an idea for MDT is it possible to implement some kind of system where officers can mark themselves 10-7, 10-8, etc within MDT itself? And that is visible to all officers. Be good for patrol Sargent's that like to keep track of what officers are doing like myself.

**Comment by teddythedev** [comment]
Probably will be added when it gets moved into city
