### ISSUE TITLE
[SUGGESTION] - BIRTHDAY DEPARTMENT

### ISSUE THREAD

**Issue by nunsia** [teddythedev/legacy-mdt-issue-tracker#21]
**Summary:**
SUP BITCH CAN YOU PLEASE ADD A DEPARTMENT ON THE CALENDER CALLED 'BIRTHDAY' TO ADD SPECIFICALLY FOR BIRTHDAYS THAT EVERYONE CAN SEE WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Reason:**
GOOD SUGGESTION BECAUSE I SUGGESTED IT WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by teddythedev** [comment]
This is completed. You can go in an edit the "Department/Divison" to Birthday in the dropdown.
