### ISSUE TITLE
[SUGGESTION] - On Duty DOC

### ISSUE THREAD

**Issue by enutpeanut** [teddythedev/legacy-mdt-issue-tracker#24]
**Summary:**
In the same way the current on-duty officers and EMS are shown on the MDT dashboard, there would also be a section for the Department of Corrections.

**Reason:**
DOC have more active staff now, and are very intertwined with PD roleplay. Would be as useful - if not more - than being able to see the on-duty EMS.

**Comment by teddythedev** [comment]
https://i.teddythedev.com/1BHMljpwHX484778.png

Working on MDT v2 and that has already been added!
