### ISSUE TITLE
[SUGGESTION] - P.C. 816 Tampering with a Motor Vehicle

### ISSUE THREAD

**Issue by enutpeanut** [teddythedev/legacy-mdt-issue-tracker#25]
**Summary:**
Add P.C. 816 Tampering with a Motor Vehicle to the MDT charges.
"Injure, tamper, break, or remove any part of a vehicle, or it's contents, without the consent of the owner."
5 Months, $500 Fine

**Reason:**
It's a charge listed in the penal code that is not in the MDT.

**Comment by teddythedev** [comment]
https://i.teddythedev.com/Jlx1PjF5bK1307302.png

That has now been added!

**Comment by teddythedev** [comment]
![Jlx1PjF5bK1307302](https://user-images.githubusercontent.com/47933692/230144267-bfe699b9-960c-4fd5-b536-69fae7e05e0b.png)
