### ISSUE TITLE
[SUGGESTION] - Add Missing Charges

### ISSUE THREAD

**Issue by ExsertRook** [teddythedev/legacy-mdt-issue-tracker#29]
**Summary:**
If possible to add the following charges to the current MDT
P.C. 911  Possession of Extended Magazines
P.C. 912  Possession of Silencers

**Reason:**
So that we can charge people properly when they have possessions of anything above

**Comment by teddythedev** [comment]
![image](https://github.com/teddythedev/legacy-mdt-issue-tracker/assets/47933692/fae99729-39bc-4d1c-976e-22b1b3ba171a)

Added!
