### ISSUE TITLE
[BUG] - On duty tab

### ISSUE THREAD

**Issue by puppyani** [teddythedev/legacy-mdt-issue-tracker#3]
**Summary:**
ST-414 Robyn Nyxx - doesn't show up on the 'On Duty', not sure if any other officers are also experiencing this issue. The MDT counts my hours just fine when clocked on duty, but never shows me in the on duty tab or list if you go into an incident and select what officers where involved.

**Steps to Reproduce / Expected Results / Actual Results:**
Not sure how to reproduce other than every time I've been on duty the last couple of weeks I haven't shown in the 'On Duty' officers!

**Comment by TheOneLizard** [comment]
this might be the same issue I had back in the day. there may be a mistype in your fivem hex on the PD roster causing this issue, as it did exactly that with me
Maybe post that hex here and if it's that issue, it'll be fixed quickly.
