### ISSUE TITLE
[SUGGESTION] Add title attribute to Tags/Persons Involved/Officers Involved elements.

### ISSUE THREAD

**Issue by CloudTheWolf** [teddythedev/legacy-mdt-issue-tracker#4]
**Summary:**
For each of the Tags/Persons Involved/Officers Involved elements, add the "title" attribute, so that in the event the details get cut off, users can hover over them to see the details.

**Reason:**
Why would your suggestion be a good change for the MDT?
When Adding Persons to the Incident (Hostages etc), if they have a long name, it gets cut off 

Eg 

`Jaiden Higgins-Black (181-3301)` will show as `Jaiden Higgins-Black (181-33..`
Adding the title attribute, with the same value as the text in element will allow officers to hover over the item to see the full details

**Comment by teddythedev** [comment]
Completed 

![image](https://user-images.githubusercontent.com/47933692/184396200-154fa222-07c5-4957-8408-46c70a0cf488.png)
