### ISSUE TITLE
[BUG] - Saving Incident White Page Issue

### ISSUE THREAD

**Issue by CloudTheWolf** [teddythedev/legacy-mdt-issue-tracker#8]
**Summary:**
Write a short summary of what you are experiencing.

**Steps to Reproduce:**
Update any issue and click save

**Expected Results:**
Incident saves and takes you back to the Created/updated incident

**Actual Results:**
What are the actual results?
Incident saves but leaves you on a white page

**Comment by teddythedev** [comment]
Fixed in latest release
